<?php

namespace Database\Seeders;

use App\Models\PageSeo;
use Illuminate\Database\Seeder;

class PageSeoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $pages = [
            [
                'page_key'         => 'home',
                'page_name'        => 'Home Page',
                'page_route'       => '/',
                'meta_title'       => 'Raghuvir Atta | 100% Pure Chakki Fresh Wheat & Multi-Grain Flour',
                'meta_description' => 'Experience the authentic taste of traditional stone-ground Chakki Fresh Atta by Raghuvir. High fiber, zero preservatives, 100% pure whole wheat nutrition.',
                'meta_keywords'    => 'raghuvir atta, chakki fresh atta, pure wheat flour, MP sharbati atta, multigrain atta, fresh flour mill, traditional stoneground atta',
                'canonical_url'    => null,
                'og_title'         => 'Raghuvir Atta - Pure & Healthy Chakki Fresh Flour',
                'og_description'   => 'Wholesome nutrition with 100% stoneground pure wheat flour. Making soft, fluffy rotis every day.',
                'og_image'         => 'images/slider-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'Organization',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'about',
                'page_name'        => 'About Us',
                'page_route'       => '/about',
                'meta_title'       => 'About Us | Raghuvir Atta - Heritage of Purity & Excellence',
                'meta_description' => 'Discover the story behind Raghuvir Atta. Decades of commitment to sourcing premium grains, authentic slow chakki milling, and delivering unadulterated goodness.',
                'meta_keywords'    => 'about raghuvir atta, chakki fresh history, flour mill journey, grain sourcing quality, pure atta company',
                'canonical_url'    => null,
                'og_title'         => 'About Raghuvir Atta - Our Heritage of Pure Milling',
                'og_description'   => 'Learn about our journey, traditional stoneground milling process, and our commitment to wholesome nutrition.',
                'og_image'         => 'images/about-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'AboutPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'products',
                'page_name'        => 'Our Products',
                'page_route'       => '/products',
                'meta_title'       => 'Premium Flours & Grains Products | Raghuvir Atta Range',
                'meta_description' => 'Explore our complete range of flours: MP Sharbati Whole Wheat Atta, Multigrain Atta, Chana Besan, Maida, and Sooji. Packed with purity and nutrition.',
                'meta_keywords'    => 'raghuvir products, wheat flour packets, multigrain flour, pure besan, suji sooji, premium atta range',
                'canonical_url'    => null,
                'og_title'         => 'Explore Raghuvir Atta Products Range',
                'og_description'   => 'High fiber, nutrition-rich flours crafted with modern hygienic standards and traditional chakki milling.',
                'og_image'         => 'images/pro-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'CollectionPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'product-details',
                'page_name'        => 'Product Details',
                'page_route'       => '/product',
                'meta_title'       => 'Product Details & Nutrition | Raghuvir Premium Flours',
                'meta_description' => 'In-depth nutritional profile, packaging sizes, dietary benefits, and culinary uses for Raghuvir stoneground flours and grains.',
                'meta_keywords'    => 'product nutrition, atta packaging, wheat flour benefits, dietary fiber flour',
                'canonical_url'    => null,
                'og_title'         => 'Raghuvir Flour Nutritional Profile & Specifications',
                'og_description'   => 'Detailed nutritional information and packaging sizes for healthy household cooking.',
                'og_image'         => 'images/pro-02.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'ItemPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'services',
                'page_name'        => 'Our Services & Milling',
                'page_route'       => '/services',
                'meta_title'       => 'Flour Milling & Bulk Supply Services | Raghuvir Atta',
                'meta_description' => 'Reliable commercial flour milling, custom grain grinding, bulk institutional supply, and private labeling services powered by advanced hygienic machinery.',
                'meta_keywords'    => 'flour milling services, bulk flour supplier, institutional atta supply, commercial grain grinding',
                'canonical_url'    => null,
                'og_title'         => 'Commercial Milling & Bulk Supply by Raghuvir',
                'og_description'   => 'Custom grain processing, commercial wholesale distribution, and specialized flour milling services.',
                'og_image'         => 'images/service-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'Service',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'service-details',
                'page_name'        => 'Service Details',
                'page_route'       => '/service-details',
                'meta_title'       => 'Milling Solutions & Bulk Capabilities | Raghuvir Atta',
                'meta_description' => 'Discover our state-of-the-art milling infrastructure, quality control testing, and customized bulk packaging for hotels, restaurants, and retail partners.',
                'meta_keywords'    => 'flour quality control, modern grain milling facility, bulk packaging capabilities',
                'canonical_url'    => null,
                'og_title'         => 'Milling Solutions & High Quality Standards',
                'og_description'   => 'Explore how Raghuvir achieves purity, consistency, and nutritional retention in every batch.',
                'og_image'         => 'images/service-02.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'Service',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'blog',
                'page_name'        => 'Blog & Recipes',
                'page_route'       => '/blog',
                'meta_title'       => 'Healthy Recipes & Nutrition Blog | Raghuvir Atta',
                'meta_description' => 'Read health tips, traditional Indian bread recipes, nutritional flour comparisons, and expert advice for a wholesome family lifestyle.',
                'meta_keywords'    => 'healthy roti recipes, atta nutrition blog, whole wheat vs multigrain, cooking tips, raghuvir blog',
                'canonical_url'    => null,
                'og_title'         => 'Raghuvir Health & Culinary Blog',
                'og_description'   => 'Delicious recipes, baking secrets, and health benefits of stoneground flours.',
                'og_image'         => 'images/blog-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'Blog',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'blog-single',
                'page_name'        => 'Blog Article View',
                'page_route'       => '/blog-details',
                'meta_title'       => 'Nutrition & Cooking Articles | Raghuvir Atta Journal',
                'meta_description' => 'Deep dive into nutrition, cooking techniques, and dietary tips with Raghuvir stoneground flours and whole grains.',
                'meta_keywords'    => 'nutrition article, flour cooking guide, soft roti recipe, digestive health atta',
                'canonical_url'    => null,
                'og_title'         => 'Raghuvir Atta Nutrition & Cooking Insights',
                'og_description'   => 'Practical health advice and culinary secrets for home cooks and food lovers.',
                'og_image'         => 'images/blog-02.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'Article',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'contact',
                'page_name'        => 'Contact Us',
                'page_route'       => '/contact',
                'meta_title'       => 'Contact Us | Wholesale Inquiries & Support | Raghuvir Atta',
                'meta_description' => 'Get in touch with Raghuvir Atta for dealership inquiries, bulk orders, customer support, or product feedback. Quick assistance and nationwide distribution support.',
                'meta_keywords'    => 'contact raghuvir atta, dealership enquiry, bulk flour order, customer care, atta supplier contact',
                'canonical_url'    => null,
                'og_title'         => 'Contact Raghuvir Atta Support & Sales',
                'og_description'   => 'Reach out to our team for bulk orders, distributor partnerships, or product questions.',
                'og_image'         => 'images/Raghuvir Logo.png',
                'robots'           => 'index, follow',
                'schema_type'      => 'ContactPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'pricing',
                'page_name'        => 'Pricing & Plans',
                'page_route'       => '/pricing',
                'meta_title'       => 'Fair & Transparent Pricing | Raghuvir Atta Packs',
                'meta_description' => 'Check our transparent pricing across retail packs, monthly household subscription packages, and bulk commercial orders.',
                'meta_keywords'    => 'atta prices, wholesale flour cost, monthly grocery atta packs, wheat flour rates',
                'canonical_url'    => null,
                'og_title'         => 'Raghuvir Atta - Affordable, Transparent Pricing',
                'og_description'   => 'Premium stoneground quality at fair, honest prices for every family.',
                'og_image'         => 'images/slider-02.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'WebPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'testimonials',
                'page_name'        => 'Customer Testimonials',
                'page_route'       => '/testimonials',
                'meta_title'       => 'Customer Reviews & Feedback | Raghuvir Atta',
                'meta_description' => 'See what homemakers, chefs, and restaurant owners say about the soft rotis, aroma, and consistency of Raghuvir Chakki Fresh Atta.',
                'meta_keywords'    => 'raghuvir atta reviews, customer testimonials, best atta ratings, roti soft reviews',
                'canonical_url'    => null,
                'og_title'         => 'What Families Say About Raghuvir Atta',
                'og_description'   => 'Trusted by thousands of happy families and commercial kitchens.',
                'og_image'         => 'images/testi-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'WebPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'faqs',
                'page_name'        => 'Frequently Asked Questions',
                'page_route'       => '/faqs',
                'meta_title'       => 'Frequently Asked Questions (FAQ) | Raghuvir Atta',
                'meta_description' => 'Got questions about stone milling, grain sourcing, shelf life, gluten content, or bulk delivery? Find answers in our comprehensive FAQ.',
                'meta_keywords'    => 'atta faq, flour shelf life, whole wheat gluten questions, chakki milling faqs',
                'canonical_url'    => null,
                'og_title'         => 'Raghuvir Atta FAQs - Everything You Need to Know',
                'og_description'   => 'Answers to common questions regarding our grains, processing, storage, and orders.',
                'og_image'         => 'images/Raghuvir Logo.png',
                'robots'           => 'index, follow',
                'schema_type'      => 'FAQPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'image-gallery',
                'page_name'        => 'Photo Gallery',
                'page_route'       => '/image-gallery',
                'meta_title'       => 'Photo Gallery | Milling Facility & Products | Raghuvir Atta',
                'meta_description' => 'Take a visual tour inside our modern stoneground chakki milling facility, quality testing laboratory, and packaging lines.',
                'meta_keywords'    => 'flour mill photos, chakki plant images, grain testing photos, raghuvir gallery',
                'canonical_url'    => null,
                'og_title'         => 'Inside Raghuvir Atta - Production & Quality Gallery',
                'og_description'   => 'See our clean, hygienic manufacturing premises and high-grade grains.',
                'og_image'         => 'images/gallery-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'ImageGallery',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'video-gallery',
                'page_name'        => 'Video Gallery',
                'page_route'       => '/video-gallery',
                'meta_title'       => 'Video Gallery | Milling Process & Stories | Raghuvir Atta',
                'meta_description' => 'Watch how traditional chakki stones slowly grind wholesome wheat into soft, nutritious flour while locking in natural nutrients.',
                'meta_keywords'    => 'chakki milling video, flour manufacturing process, farm to table story video',
                'canonical_url'    => null,
                'og_title'         => 'Watch How Raghuvir Atta Is Made',
                'og_description'   => 'Video stories showcasing our slow stoneground milling tradition and pure ingredients.',
                'og_image'         => 'images/gallery-02.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'VideoGallery',
                'is_active'        => true,
            ],
            [
                'page_key'         => 'team',
                'page_name'        => 'Our Team',
                'page_route'       => '/team',
                'meta_title'       => 'Our Leadership & Milling Experts | Raghuvir Atta',
                'meta_description' => 'Meet the passionate team behind Raghuvir Atta dedicated to agricultural purity, precision milling, and quality customer service.',
                'meta_keywords'    => 'raghuvir leadership, flour mill team, agricultural experts',
                'canonical_url'    => null,
                'og_title'         => 'The People Behind Raghuvir Purity',
                'og_description'   => 'Dedicated milling artisans, nutritionists, and quality control experts.',
                'og_image'         => 'images/team-01.jpg',
                'robots'           => 'index, follow',
                'schema_type'      => 'AboutPage',
                'is_active'        => true,
            ],
            [
                'page_key'         => '404',
                'page_name'        => 'Page Not Found (404)',
                'page_route'       => '/404',
                'meta_title'       => 'Page Not Found | Raghuvir Atta',
                'meta_description' => 'The page you are looking for might have been moved or does not exist. Explore our pure chakki fresh atta products and recipes.',
                'meta_keywords'    => '404, page not found, raghuvir atta',
                'canonical_url'    => null,
                'og_title'         => 'Page Not Found - Raghuvir Atta',
                'og_description'   => 'Head back to our homepage to explore our complete wholesome flour range.',
                'og_image'         => 'images/Raghuvir Logo.png',
                'robots'           => 'noindex, nofollow',
                'schema_type'      => 'WebPage',
                'is_active'        => true,
            ],
        ];

        foreach ($pages as $data) {
            PageSeo::updateOrCreate(
                ['page_key' => $data['page_key']],
                $data
            );
        }
    }
}
